name: memoized
description: Decorators to cache returned values, it helps in reducing the execution time of the function by using LRU Caching.
version: 1.4.7
repository: https://github.com/sylfree/memoized

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  to_string_pretty: ^1.1.5
  tuple: ^2.0.0
  quiver: ^3.0.1
  
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
