name: memoized
description: Decorators to cache returned values, it helps in reducing the execution time of the function by using LRU Caching.
version: 2.2.2
repository: https://github.com/sylfreee/memoized

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  quiver: ^3.2.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
